### ISSUE TITLE
zlib context is connection scope, not stream scope

### ISSUE THREAD

**Issue by tatsuhiro-t** [bagder/spindly#1]
In spdy_syn_stream_parse(), zlib context is created for each stream.
But spdy/2 requires zlib context is created for each connection.
I think zlib context should be moved to struct spindly_phys.

Feel free to close this issue as invalid if this is intentional.

**Comment by bagder** [comment]
Whoa, oops! Thanks a lot for the heads up, I'll certainly move it.

**Comment by bagder** [comment]
I moved it and pushed my fix now, closing this. Thanks again!
